// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// ERRORS
export const SET_ERRORS = 'SET_ERRORS';

// AUTH
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_LOADING = 'USER_LOADING';
export const AUTHENTIACTION_ERROR = 'AUTHENTIACTION_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

// PROFILE
export const USER_PROFILE_FETCH_SUCCESS = 'USER_PROFILE_FETCH_SUCCESS';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const SET_IS_CURRENT_USER = 'SET_IS_CURRENT_USER';
export const RESET_PROFILE = 'RESET_PROFILE';

// PROFILES
export const PROFILES_ERROR = 'PROFILES_ERROR';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';
export const PROFILES_FETCH_SUCCESS = 'PROFILES_FETCH_SUCCESS';
export const RECOMMENDED_PROFILES_FETCH_SUCCESS = 'RECOMMENDED_PROFILES_FETCH_SUCCESS';
export const CLEAR_RECOMMENDED_PROFILES = 'CLEAR_RECOMMENDED_PROFILES';
export const MORE_PROFILES_LOADING = 'MORE_PROFILES_LOADING';
export const MORE_PROFILES_FETCH_SUCCESS = 'MORE_PROFILES_FETCH_SUCCESS';
export const PROFILES_LOADING = 'PROFILES_LOADING';
export const SEARCH_CONSTANTS_FETCH_SUCCESS = 'SEARCH_CONSTANTS_FETCH_SUCCESS';
